operator_address = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"

# This is the address of the contracts which are deployed in the anvil saved state
# The saved eigenlayer state is located in tests/anvil/credible_squaring_avs_deployment_output.json
# TODO: automate updating these addresses when we deploy new contracts

# Core deployment
allocation_manager_address = "0x2279b7a0a67db372996a5fab50d91eaa73d2ebe6"
delegation_manager_address = "0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0"
rewards_coordinator_address = "0xa51c1fc2f0d1a1b8494ed1fe312d7c3a78ed91c0"
permission_controller_address = "0x59b670e9fa9d0a427751af201d676719a970857b"

# Avs deployment
service_manager_address = "0x5f3f1dbd7b74c6b46e8c44f98792a1daf8d69154"
registry_coordinator_address = "0x7bc06c482dead17c0e297afbc32f6e63d3846650"
token_strategy_addr = "0x2b961e3959b79326a8e7f64ef0d2d825707669b5"

ecdsa_private_key_store_path = "tests/keys/test.ecdsa.key.json"
bls_private_key_store_path = "tests/keys/test.bls.key.json"

# Node URLs
eth_http_url = "http://localhost:8545"
eth_ws_url = "ws://localhost:8545"

aggregator_server_ip_port = "localhost:8090"

task_manager_address = "0x2bdcc0de6be1f7d2ee689a0342d76f52e8efaba3"
