name: check that make fmt was run
on:
  push:
    branches:
      - dev
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  check-make-fmt:
    name: check make fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install go1.21
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Run make fmt
        run: make fmt
      
      - name: Check if make fmt generated changes that should be committed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Error: make fmt generated changes that should be committed. Please run 'make fmt' and commit the changes."
            git diff
            git status
            exit 1
          fi
