name: Daily Build And Test Dev

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  check:
    strategy:
      fail-fast: true
    defaults:
      run:
        working-directory: ./contracts

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test