name: Check Storage Layout
on:
  pull_request:
    branches:
      - master
      - dev
jobs:
  check_storage:
    runs-on: "ubuntu-latest"
    steps:
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - uses: actions/checkout@v4
        with:
          submodules: recursive
          path: head

      - name: "Generate and prepare HEAD artifacts"
        working-directory: head/contracts
        run: |
          mkdir storage
          for file in $(find src -name '*.sol'); do
              contract_name=$(basename "$file" .sol)
              forge inspect "$contract_name" storage > storage/"$contract_name".md
          done

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          submodules: recursive
          path: base

      - name: "Generate and prepare BASE artifacts"
        working-directory: base/contracts
        run: |
          mkdir storage
          for file in $(find src -name '*.sol'); do
              contract_name=$(basename "$file" .sol)
              forge inspect "$contract_name" storage > storage/"$contract_name".md
          done

      - name: Compare outputs
        run: |
          if ! diff --unified head/contracts/storage base/contracts/storage; then
            # Note: We are only creating a warning because storage changes might be intentional but should be looked into
            # reach out to steven if you see a warning on this workflow and need help validating if it is expected or not
            echo "::warning::Differences found between PR and base storage layouts"
          fi
